# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
games_supported = [
  'Halo 5:Guardians',
  'Halo:The Master chief Collection',
  'Halo 4',
  'Halo Reach',
  'Halo 3:ODST',
  'Halo Wars',
  'Halo 3',
  'Halo 2',
  'Halo:2600',
  'Call of Duty:Infinite Warfare',
  'Call of Duty:Black Ops 3',
  'Call of Duty:Advanced Warfare',
  'Call of Duty:Ghosts',
  'Call of Duty:Black Ops 2',
  'Call of Duty:Modern Warfare 3',
  'Call of Duty:Black Ops',
  'Call of Duty:Modern Warfare 2',
  'Call of Duty:World at War',
  'Call of Duty:Modern Warfare',
  'Call of Duty 3',
  'Call of Duty 2',
  'Overwatch',
  'Battleborn',
  'Destiny',
  'Uncharted 2 Among Thieves',
  "Uncharted 3 Drake's Deception",
  "Uncharted 4 A Thief's End",
  "The Last of Us",
  'Titanfall',
  'Dark Souls 3',
  'Dark Souls 2',
  'The Division',
  'DOOM: 2',
  'Star Wars:Battlefront  2',
  'Diablo 3:Reaper of Souls',
  'Far Cry 4',
  'Borderlands:The Handsome Collection',
  'Borderlands 2',
  'Borderlands',
  'Grand Theft Auto V',
  'Grand Theft Auto Iv',
  'FIFA 17',
  'FIFA 16',
  'FIFA 15',
  'FIFA 14',
  'Madden nfl 17',
  'Madden nfl 16',
  'Madden nfl 15',
  'Madden nfl 14',
  'Madden nfl 13',
  'Gears of War:Ultimate Edition: 1',
  'Gears of War 4',
  'Gears of War:Judgment',
  'Gears of War 3',
  'Gears of War 2',
  'Gears of War',
  'Sunset Overdrive',
  'Rocket League',
  'Homefront:The Revolution',
  'Dead Rising 3',
  'Dying Light',
  'NBA Live 09',
  'NBA 2K17',
  'NBA 2K16',
  'NBA 2K15',
  'NBA 2K14',
  'MLB The Show 15',
  'Killer Instinct: 1',
  'Forza Motorsport 6',
  'Forza Horizon 2',
  'Forza Motorsport 5',
  'Forza Horizon',
  'Forza Motorsport 4',
  'Gran Turismo 6',
  'Gran Turismo 5',
  'LittleBigPlanet 3',
  'LittleBigPlanet 2',
  'LittleBigPlanet',
  'Tekken 5',
  'Tekken 6',
  'Tekken 7',
  'Street Fighter Iv',
  'Street Fighter V',
  'Plants vs Zombies:Garden Warfare',
  'Plants vs Zombies:Garden Warfare 2',
  'Driveclub',
  'Project CARS',
  'The Crew',
  'Driveclub',
  "Assassin's Creed Unity",
  "Rayman Legends",
  "Dragon Ball Xenoverse",
  "NHL 17",
  "NHL 16",
  "NHL 15",
  "NHL 14",
  "WWE 2K17",
  "WWE 2K16",
  "WWE 2K15",
  "WWE 2K14",
  "EA Sports UFC",
  "UFC Undisputed 3",
  "Mortal Kombat X",
  "Naruto Shippuden:Ultimate Ninja Storm 4",
  "Tom Clancy's Rainbow Six:Shadow Vanguard",
  'Pro Evolution Soccer 2016',
  'Battlefield 1',
  'Battlefield Hardline',
  'Battlefield 4',
  'Battlefield 3',
  "Minecraft:Story mode",
  "The Witcher 3:Wild Hunt",
  "The Witcher 2:Assassins of Kings",
  "Borderlands 2",
  "Mass Effect",
  "Mass Effect 2",
  "Mass Effect 3",
  "Dragon Age:Inquisition",
  "Bloodborne",
  "Wolfenstein:The New Order",
  "Watch Dogs",
  "Assassin's Creed Iv:Black Flag",
  "Middle-earth:Shadow of Mordor",
  "Fallout 4",
  "Metal Gear Solid V:Ground Zeroes",
  "Saints Row IV",
  "Red Dead Redemption",
  "Bioshock Infinite",
  "Fallout:New Vegas",
  "Assassin's Creed:Brotherhood",
  "Max Payne 3",
  "Spec Ops:The Line",
  "XCOM:Enemy Unknown",
  "Far Cry 3",
  "Sleeping Dogs",
  "Hotline Miami",
  "Dead Space 2",
  "God of War III",
  "Dead Island",
  "Counter-Strike:Global Offensive",
  "Borderlands",
  "Saints Row:The Third",
  "Payday 2",
  "Deus Ex:Human Revolution",
  "South Park:The Stick of Truth",
  "Battlefield:Bad Company 2",
  "The Order:1886",
  "Evolve",
  "Tom Clancy's Rainbow Six:Siege  1",
  "Assassins Creed Chronicles:India",
  "Hotline Miami 2:Wrong Number",
  "Assassin's Creed:Rogue"
]


games_supported.sort.each do |name|
  Game.find_or_create_by(name: name)
end
