# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
games_supported = [
 'Halo 5: Guardians',
 'Halo: The Masterchief Collection',
 'Halo 4',
 'Halo: Reach',
 'Halo 3: ODST',
 'Halo Wars',
 'Halo 3',
 'Halo 2',
 'Halo',
 'Call of Duty: Infinite Warfare',
 'Call of Duty: Black Ops 3',
 'Call of Duty: Advanced Warfare',
 'Call of Duty: Ghosts',
 'Call of Duty: Black Ops 2',
 'Call of Duty: Modern Warfare 3',
 'Call of Duty: Black Ops',
 'Call of Duty: Modern Warfare 2',
 'Call of Duty: World at War',
 'Call of Duty: Modern Warfare',
 'Call of Duty 3',
 'Call of Duty 2',
 'Overwatch',
 'Battleborn',
 'Destiny',
 'Uncharted 2: Among Thieves',
 "Uncharted 3: Drake's Deception",
 "Uncharted 4: A Thief's End",
 "The Last of Us",
 'Titanfall',
 'Dark Souls 3',
 'Dark Souls 2',
 'The Division',
 'DOOM',
 'Star Wars: Battlefront',
 'Diablo 3: Ultimate Evil Edition',
 'Far Cry 4',
 'Borderlands: The Handsome Collection',
 'Borderlands 2',
 'Borderlands',
 'Grand Theft Auto 5',
 'Grand Theft Auto 4',
 'FIFA 17',
 'FIFA 16',
 'FIFA 15',
 'FIFA 14',
 'Madden 17',
 'Madden 16',
 'Madden 15',
 'Madden 25',
 'Madden 13',
 'Gears of War: Ultimate Edition',
 'Gears of War 4',
 'Gears of War: Judgement',
 'Gears of War 3',
 'Gears of War 2',
 'Gears of War',
 'Sunset Overdrive',
 'Rocket League',
 'Homefront: The Revolution',
 'Dead Rising 3',
 'Dying Light',
 'NBA Live',
 'NBA 2K17',
 'NBA 2K16',
 'NBA 2K15',
 'NBA 2K14',
 'MLB 15: The Show',
 'Killer Instinct',
 'Forza Motorsport 6',
 'Forza Horizon 2',
 'Forza Motorsport 5',
 'Forza Horizon',
 'Forza Motorsport 4',
 'Gran Turismo 6',
 'Gran Turismo 5',
 'LittleBigPlanet 3',
 'LittleBigPlanet 2',
 'LittleBigPlanet',
 'Tekken 5',
 'Tekken 6',
 'Tekken 7',
 'Street Fighter 4',
 'Street Fighter 5',
 'Plants vs. Zombies: Garden Warfare',
 'Plants vs. Zombies: Garden Warfare 2',
 'Driveclub',
 'Project CARS',
 'The Crew',
 'Driveclub',
 "Assassin's Creed Unity",
 "Rayman Legends",
 "Dragon Ball Xenoverse",
 "NHL 17",
 "NHL 16",
 "NHL 15",
 "NHL 14",
 "WWE 2K17",
 "WWE 2K16",
 "WWE 2K15",
 "WWE 2K14",
 "UFC 2",
 "UFC",
 "Mortal Kombat X",
 "Naruto Shippuden: Ultimate Ninja Storm 4",
 "Rainbow Six Seige",
 'PES 2016',
 'Battlefield 1',
 'Battlefield Hardline',
 'Battlefield 4',
 'Battlefield 3',
 "Minecraft: PlayStation 4 Edition"]


games_supported.sort.each do |name|
 Game.create(name: name)
end
